### ISSUE TITLE
Investigate adding Babel to our pipeline

### ISSUE THREAD

**Issue by raphaelschaad** [raphaelschaad/Plus-Web#14]
https://babeljs.io

Then we could enable arrow functions (not supported by IE11) again: https://github.com/raphaelschaad/Plus-Web/pull/6/commits/864f903275c277e0867eef9fea3c1ebf669dcc4b#diff-e4403a877d80de653400d88d85e4801aR32

**Comment by raphaelschaad** [comment]
Babel will come as a dependency of a package I use in #18.

**Comment by xaverfleer** [comment]
#26 (1c34829) adds Babel to our pipeline
