### ISSUE TITLE
HTML ID attributes must be unique in each document

### ISSUE THREAD

**Issue by xaverfleer** [raphaelschaad/Plus-Web#45]
> The id global attribute defines an identifier (ID) which must be unique in the whole document [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id)

Found duplicate: `<section id="library">` in`\public\index.html`.

If an identifier is used more than once, use a class instead.

**Comment by raphaelschaad** [comment]
Great find. How did you find it? Shall I fix it?

**Comment by xaverfleer** [comment]
I found it just by reading the code.

Sure, fix it if you find the time. But there is no hurry.

Also: If you fix it, take into account that it might have an impact on the rendering because the CSS specificity changes (ID's are stronger than classes).

**Comment by raphaelschaad** [comment]
I've just pulled up [the code](https://github.com/raphaelschaad/Plus-Web/blob/master/public/index.html#L132), how is it used more than once?

**Comment by xaverfleer** [comment]
You are right: in `\public\index.html` the id exists only once. sorry

in the following files it exists twice:
`public\demo\admin.html`,
`public\demo\prescribed.html`,
`public\zfbc\admin.html`,
`public\zfbc\prescribed.html`

![idLibrary](https://user-images.githubusercontent.com/7235734/61125097-29400300-a4a9-11e9-83e6-0d90084acd0e.png)

**Comment by raphaelschaad** [comment]
Addressed by https://github.com/raphaelschaad/Plus-Web/commit/433f5668446fefe54f03e31f14f34482d43c54c3 -- From what I can tell, there was no (undesired) visual difference in removing the id altogether (for now).
